patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "latest"
rv-brand = "ReVanced Zygisk"
remove-rv-integrations-checks = true
enable-module-update = true

[YouTube]
app-name = "YouTube"
enabled = true
build-mode = "module"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-revanced-zygisk"
